// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmnetjyhrquukdzywjuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtbmV0anlocnF1dWtkenl3anV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzQ2OTEsImV4cCI6MjA3MTAxMDY5MX0.MAIgfQOJYGE0crp4PQK6puN9XMzV-K3bM2M5DUmYcaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});